pokemastertext:
- 你几把谁啊, 竟敢戳我亲爱滴主人, 胆子好大啊你

pokecount:
 - _name_今天已经被戳了_num_次啦，休息一下好不好
 - _name_今天已经被戳了_num_次啦，有完没完！
 - _name_今天已经被戳了_num_次啦，要戳坏掉了！
 - _name_今天已经被戳了_num_次啦，别戳了!!!
 - _name_今天已经被戳了_num_次啦，不准戳了！！！
 - _name_今天已经被戳了_num_次啦，再戳就坏了！

poketext:
 - 被戳晕了……轻一点啦！
 - 救命啊，有变态>_<！！！
 - 哼~~~
 - 你戳谁呢！你戳谁呢！！！           o(´^｀)o
 - 唔，这触感有种被兰那罗拿胡萝卜指着的感觉≥﹏≤
 - 不要再戳了！我真的要被你气死了！！！
 - 怎么会有你这么无聊的人啊！！！(￢_￢)
 - 把嘴张开（抬起脚）
 - 啊……你戳疼我了Ծ‸Ծ
 - 你干嘛！
 - 你是不是喜欢我？
 - 朗达哟？
 - 变态萝莉控！
 - 要戳坏掉了>_<
 - 旅行者，你没睡醒吗？一天天就知道戳我
 - 别戳了！在戳就丢你去喂鱼
 - 你戳我干嘛,闲得蛋疼吗?
 - 手痒痒,老是喜欢戳人。
 - 你戳我,我咬你!
 - 戳来戳去,真是的... 
 - 戳我也没用,改变不了你单身的事实。
 - 戏精,你戳我有完没完?
 - 戳我干嘛,要不要脸啊你!
 - 戳人家干嘛,难道我长得很好戳?
 - 戳完了,满足你的戳癖了吧!
 - 戳我啊,等会儿我报复,就不止戳一戳那么简单!
 - 你戳我,是想逗我开心吗?那我很开心噢!
 - 没事找事,真是的
 - 拜托,旅行者你能不能消停会?
 - 行了行了,戳完了没?闹腾完了没?
 - 你再戳,_name_,您别老戳人家了行不?
 - 戳我一下,告诉我你有完没完