cnmodel:
- 派蒙
- 纳西妲
- 凯亚
- 温迪
- 荒泷一斗
- 娜维娅
- 陆景和
- 莫弈
- 左然
- 夏彦
- 神里绫华
- 凝光
- 北斗
- 迪奥娜
- 可莉
- 柯莱
- 丽莎
- 莱欧斯利
- 琳妮特
- 五郎
- 芭芭拉
- 雷电将军
- 珊瑚宫心海
- 魈
- 琴
- 胡桃
- 砂糖
- 鹿野院平藏
- 安柏
- 重云
- 夜兰
- 达达利亚
- 班尼特
- 妮露
- 香菱
- 珐露珊
- 迪卢克
- 刻晴
- 烟绯
- 辛焱
- 早柚
- 夏洛蒂
- 夏沃蕾
- 优菈
- 云堇
- 久岐忍
- 神里绫人
- 甘雨
- 流浪者
- 行秋
- 千织
- 戴因斯雷布
- 闲云
- 白术
- 菲谢尔
- 申鹤
- 九条裟罗
- 雷泽
- 荧
- 空
- 嘉明
- 菲米尼
- 多莉
- 迪娜泽黛
- 凯瑟琳
- 绮良良
- 罗莎莉亚
- 米卡
- 坎蒂丝
- 萍姥姥
- 留云借风真君
- 爱贝尔
- 伊迪娅
- 瑶瑶
- 七七
- 式大将
- 奥兹
- 泽维尔
- 哲平
- 大肉丸
- 托克
- 蒂玛乌斯
- 塞琉斯
- 欧菲妮
- 昆钧
- 言笑
- 仆人
- 迈勒斯
- 希格雯
- 拉赫曼
- 杜拉夫
- 克洛琳德
- 伊利亚斯
- 爱德琳
- 玛乔丽
- 柊千里
- 九条镰治
- 塞塔蕾
- 海芭夏
- 笼钓瓶一心
- 叶德
- 卡莉露
- 查尔斯
- 莎拉
- 玛格丽特
- 博来
- 纳比尔
- 迪尔菲
- 康纳
- 玛塞勒
- 博士
- 宛烟
- 羽生田千鹤
- 海妮耶
- 天叔
- 鹿野奈奈
- 一心传名刀
- 弗洛朗
- 舒伯特
- 莺儿
- 龙二
- 梅里埃
- 芙卡洛斯
- 嘉良
- 珊瑚
- 久利须
- 费迪南德
- 嘉玛
- 艾伯特
- 天目十五
- 女士
- 丹吉尔
- 白老先生
- 吴船长
- 巴达维
- 拉齐
- 长生
- 莫塞伊思
- 杜吉耶
- 斯坦利
- 百闻
- 掇星攫辰天君
- 迈蒙
- 博易
- 花角玉将
- 知易
- 上杉
- 大慈树王
- 田铁嘴
- 常九爷
- 西拉杰
- 沙扎曼
- 深渊使徒
- 安西
- 三月七
- 丹恒
- 瓦尔特
- 希儿
- 希露瓦
- 米卡洛
- 流萤
- 桂乃芬
- 托帕
- 真理医生
- 彦卿
- 黑塔
- 驭空
- 停云
- 玲可
- 镜流
- 罗刹
- 银狼
- 阮•梅
- 青雀
- 阿兰
- 米沙
- 浮烟
- 帕姆
- 螺丝咕姆
- 加拉赫
- 卢卡
- 史瓦罗
- 明曦
- 寒鸦
- 雪衣
- 银枝
- 晴霓
- 丹枢
- 星期日
- 尾巴
- 花火
- 可可利亚
- 青镞
- 半夏
- 刃
- 霄翰
- 信使
- 卡卡瓦夏
- 钟表小子
- 岩明
- 浣溪
- 知更鸟
- Lumi


jpmodel:


enmodel:


api2model:
  - 空
  - 荧
  - 派蒙
  - 纳西妲
  - 阿贝多
  - 温迪
  - 枫原万叶
  - 钟离
  - 荒泷一斗
  - 八重神子
  - 艾尔海森
  - 提纳里
  - 迪希雅
  - 卡维
  - 宵宫
  - 莱依拉
  - 赛诺
  - 诺艾尔
  - 托马
  - 凝光
  - 莫娜
  - 北斗
  - 神里绫华
  - 雷电将军
  - 芭芭拉
  - 鹿野院平藏
  - 五郎
  - 迪奥娜
  - 凯亚
  - 安柏
  - 班尼特
  - 琴
  - 柯莱
  - 夜兰
  - 妮露
  - 辛焱
  - 珐露珊
  - 魈
  - 香菱
  - 达达利亚
  - 砂糖
  - 早柚
  - 云堇
  - 刻晴
  - 丽莎
  - 迪卢克
  - 烟绯
  - 重云
  - 珊瑚宫心海
  - 胡桃
  - 可莉
  - 流浪者
  - 久岐忍
  - 神里绫人
  - 甘雨
  - 戴因斯雷布
  - 优菈
  - 菲谢尔
  - 行秋
  - 白术
  - 九条裟罗
  - 雷泽
  - 申鹤
  - 迪娜泽黛
  - 凯瑟琳
  - 多莉
  - 坎蒂丝
  - 萍姥姥
  - 罗莎莉亚
  - 留云借风真君
  - 绮良良
  - 瑶瑶
  - 七七
  - 奥兹
  - 米卡
  - 夏洛蒂
  - 埃洛伊
  - 博士
  - 女士
  - 大慈树王
  - 三月七
  - 娜塔莎
  - 希露瓦
  - 虎克
  - 克拉拉
  - 丹恒
  - 希儿
  - 布洛妮娅
  - 瓦尔特
  - 杰帕德
  - 佩拉
  - 姬子
  - 艾丝妲
  - 白露
  - 星
  - 穹
  - 桑博
  - 伦纳德
  - 停云
  - 罗刹
  - 卡芙卡
  - 彦卿
  - 史瓦罗
  - 螺丝咕姆
  - 阿兰
  - 银狼
  - 素裳
  - 丹枢
  - 黑塔
  - 景元
  - 帕姆
  - 可可利亚
  - 半夏
  - 符玄
  - 公输师傅
  - 奥列格
  - 青雀
  - 大毫
  - 青镞
  - 费斯曼
  - 绿芙蓉
  - 镜流
  - 信使
  - 丽塔
  - 失落迷迭
  - 缭乱星棘
  - 伊甸
  - 伏特加女孩
  - 狂热蓝调
  - 莉莉娅
  - 萝莎莉娅
  - 八重樱
  - 八重霞
  - 卡莲
  - 第六夜想曲
  - 卡萝尔
  - 姬子
  - 极地战刃
  - 布洛妮娅
  - 次生银翼
  - 理之律者
  - 真理之律者
  - 迷城骇兔
  - 希儿
  - 魇夜星渊
  - 黑希儿
  - 帕朵菲莉丝
  - 天元骑英
  - 幽兰黛尔
  - 德丽莎
  - 月下初拥
  - 朔夜观星
  - 暮光骑士
  - 明日香
  - 李素裳
  - 格蕾修
  - 梅比乌斯
  - 渡鸦
  - 人之律者
  - 爱莉希雅
  - 爱衣
  - 天穹游侠
  - 琪亚娜
  - 空之律者
  - 终焉之律者
  - 薪炎之律者
  - 云墨丹心
  - 符华
  - 识之律者
  - 维尔薇
  - 始源之律者
  - 芽衣
  - 雷之律者
  - 苏莎娜
  - 阿波尼亚
  - 陆景和
  - 莫弈
  - 夏彦
  - 左然
