cnmodel:
- 埃德
- 塔杰·拉德卡尼
- 行秋
- 深渊使徒
- 凯瑟琳
- 常九爷
- 神里绫人
- 丽莎
- 纯水精灵?
- 宛烟
- 重云
- 悦
- 莱依拉
- 鹿野奈奈
- 式大将
- 白术
- 埃舍尔
- 莫娜
- 优菈
- 琴
- 凯亚
- 西拉杰
- 凝光
- 石头
- 达达利亚
- 伊利亚斯
- 艾尔海森
- 慧心
- 大肉丸
- 柊千里
- 玛乔丽
- 神里绫华
- 菲米尼
- 甘雨
- 掇星攫辰天君
- 坎蒂丝
- 上杉
- 阿尔卡米
- 戴因斯雷布
- 艾文
- 回声海螺
- 九条裟罗
- 迪卢克
- 提纳里
- 嘉良
- 塞塔蕾
- 琳妮特
- 阿洛瓦
- 蒂玛乌斯
- 枫原万叶
- 丹吉尔
- 空
- 林尼
- 阿守
- 七七
- 嘉玛
- 恶龙
- 阿巴图伊
- 阿佩普
- 八重神子
- 迪希雅
- 迈勒斯
- 夜兰
- 萨赫哈蒂
- 欧菲妮
- 笼钓瓶一心
- 芭芭拉
- 瑶瑶
- 天叔
- 派蒙
- 米卡
- 玛塞勒
- 胡桃
- 百闻
- 艾莉丝
- 安柏
- 阿晃
- 萨齐因
- 田铁嘴
- 烟绯
- 海妮耶
- 纳比尔
- 女士
- 诺艾尔
- 云堇
- 舒伯特
- 埃勒曼
- 九条镰治
- 留云借风真君
- 言笑
- 安西
- 珊瑚宫心海
- 托克
- 哲平
- 恕筠
- 拉赫曼
- 久利须
- 天目十五
- 妮露
- 莺儿
- 佐西摩斯
- 鹿野院平藏
- 温迪
- 菲谢尔
- anzai
- 可莉
- 刻晴
- 克列门特
- 阿扎尔
- 班尼特
- 伊迪娅
- 巴达维
- 深渊法师
- 赛诺
- 大慈树王
- 拉齐
- 海芭夏
- 香菱
- 康纳
- 阿祇
- 卡维
- 博来
- 斯坦利
- 霍夫曼
- 北斗
- 阿拉夫
- 陆行岩本真蕈·元素生命
- 爱贝尔
- 雷泽
- 毗伽尔
- 莎拉
- 莫塞伊思
- 多莉
- 珊瑚
- 老孟
- 宵宫
- 钟离
- 芙宁娜
- 爱德琳
- 女士
- 博易
- 长生
- 查尔斯
- 阿娜耶
- 流浪者
- 辛焱
- 德沃沙克
- 雷电将军
- 羽生田千鹤
- 那维莱特
- 沙扎曼
- 纳西妲
- 艾伯特
- 龙二
- 旁白
- 克罗索
- 元太
- 阿贝多
- 萍姥姥
- 久岐忍
- 埃洛伊
- 托马
- 迪奥娜
- 荧
- 夏洛蒂
- 莱欧斯利
- 昆钧
- 塞琉斯
- 埃泽
- 迪娜泽黛
- 知易
- 玛格丽特
- 申鹤
- 罗莎莉亚
- 娜维娅
- 珐露珊
- 浮游水蕈兽·元素生命
- 奥兹
- 砂糖
- 绮良良
- 杜拉夫
- 魈
- 松浦
- 迈蒙
- 荒泷一斗
- 吴船长
- 埃尔欣根
- 柯莱
- 阿圆
- 白老先生
- 五郎
- 博士

jpmodel:
  - 行秋
  - コナー
  - 籠釣瓶一心
  - 宛煙
  - アビスの使徒
  - ティマイオス
  - タージ·ラドカニ
  - 望雅
  - イディア
  - フレミネ
  - セノ
  - シャリフ
  - アデリン
  - イナヤ
  - 巫女
  - サーチェン
  - クンジュ
  - 淵上と自称するもの
  - ニィロウ
  - シェイクズバイル
  - 式大将
  - レオン
  - 放浪者
  - レッシグ
  - アーラヴ
  - フェルディナンド
  - 凝光
  - 小倉澪
  - マーガレット
  - 守
  - 長生
  - アルバート
  - 慧心
  - ヨォーヨ
  - 柊千里
  - 丹羽
  - アルカミ
  - 甘雨
  - モセイス
  - 掇星攫辰天君
  - 龍二
  - スクロース
  - 珊瑚宮心海
  - ヴィハル
  - マル
  - スタンレー
  - 御肉丸
  - 上杉
  - アーロイ
  - サラ
  - 純水精霊?
  - 嘉良
  - 申鶴
  - リサ
  - クリメント
  - オズ
  - アルハイゼン
  - ナヴィア
  - 孟
  - 淑女
  - 傍白
  - 空
  - 古山
  - 七七
  - サイリュス
  - ナビル
  - 雷電将軍
  - 九条裟羅
  - セタレ
  - 天おじ
  - ロサリア
  - ドゥラフ
  - 晃
  - ディオナ
  - 宵宮
  - テウセル
  - 銀杏
  - 楓原万葉
  - 夜蘭
  - 八重神子
  - レザー
  - エルザー
  - エデ
  - 神里綾人
  - 詩筠
  - 神里綾華
  - マルシラック
  - 雲菫
  - ダインスレイヴ
  - マハールッカデヴァータ
  - ジン
  - ノエル
  - ゴロー
  - ゾシモス
  - アイルマン
  - 胡桃
  - メイモム
  - アペプ
  - ベネット
  - キャンディス
  - ナーダワ
  - アイベル
  - 綺良々
  - ロレンツォ
  - 煙緋
  - ジョイン
  - ドニアザード
  - エルファネ
  - 九条鎌治
  - バダウィ
  - クロッサル
  - 鍾離
  - 言笑
  - 「カーブース」
  - トーマ
  - エウルア
  - 安西
  - ウェンティ
  - プカプカ水キノコン·元素生命
  - ファルザン
  - 哲平
  - 天目十五
  - ナヒーダ
  - 一平
  - アリス
  - アロイス
  - リネット
  - 悪龍
  - アンバー
  - 刻晴
  - 田饒舌
  - クレー
  - ラフマン
  - ラエッド
  - スカーレット
  - シコウ
  - 荒瀧一斗
  - ジェマ
  - ピンばあや
  - 香菱
  - つみ
  - 鹿野院平蔵
  - シラージ
  - 博来
  - 鶯
  - アザール
  - パイモン

enmodel:
  - 派蒙
  - 纳西妲
  - 凯亚
  - 阿贝多
  - 温迪
  - 枫原万叶
  - 钟离
  - 荒泷一斗
  - 八重神子
  - 艾尔海森
  - 迪希雅
  - 提纳里
  - 卡维
  - 宵宫
  - 莱依拉
  - 赛诺
  - 诺艾尔
  - 托马
  - 凝光
  - 莫娜
  - 北斗
  - 柯莱
  - 神里绫华
  - 可莉
  - 芭芭拉
  - 雷电将军
  - 珊瑚宫心海
  - 鹿野院平藏
  - 迪奥娜
  - 琴
  - 五郎
  - 班尼特
  - 安柏
  - 夜兰
  - 妮露
  - 辛焱
  - 珐露珊
  - 林尼
  - 丽莎
  - 魈
  - 香菱
  - 烟绯
  - 迪卢克
  - 砂糖
  - 早柚
  - 云堇
  - 刻晴
  - 重云
  - 优菈
  - 胡桃
  - 久岐忍
  - 神里绫人
  - 公子
  - 娜维娅
  - 甘雨
  - 戴因斯雷布
  - 菲谢尔
  - 行秋
  - 白术
  - 九条裟罗
  - 雷泽
  - 申鹤
  - 荧
  - 空
  - 流浪者
  - 迪娜泽黛
  - 凯瑟琳
  - 多莉
  - 坎蒂丝
  - 萍姥姥
  - 罗莎莉亚
  - 埃德
  - 夏洛蒂
  - 伊迪娅
  - 爱贝尔
  - 留云借风真君
  - 散兵
  - 那维莱特
  - 琳妮特
  - 七七
  - 式大将
  - 瑶瑶
  - 奥兹
  - 米卡
  - 达达利亚
  - 哲平
  - 绮良良
  - 浮游水蕈兽·元素生命
  - 大肉丸
  - 托克
  - 蒂玛乌斯
  - 昆钧
  - 欧菲妮
  - 塞琉斯
  - 拉赫曼
  - 阿守
  - 芙宁娜
  - 杜拉夫
  - 伊利亚斯
  - 阿晃
  - 旁白
  - 菲米尼
  - 爱德琳
  - 埃洛伊
  - 迈勒斯
  - 德沃沙克
  - 玛乔丽
  - 塞塔蕾
  - 九条镰治
  - 柊千里
  - 海芭夏
  - 阿娜耶
  - 笼钓瓶一心
  - 回声海螺
  - 元太
  - 阿扎尔
  - 查尔斯
  - 埃勒曼
  - 阿洛瓦
  - 莎拉
  - 纳比尔
  - 康纳
  - 博来
  - 阿祇
  - 玛塞勒
  - 博士
  - 玛格丽特
  - 宛烟
  - 羽生田千鹤
  - 海妮耶
  - 佐西摩斯
  - 霍夫曼
  - 舒伯特
  - 鹿野奈奈
  - 天叔
  - 龙二
  - 艾莉丝
  - 莺儿
  - 嘉良
  - 言笑
  - 费迪南德
  - 珊瑚
  - 嘉玛
  - 久利须
  - 艾文
  - 女士
  - 丹吉尔
  - 白老先生
  - 老孟
  - 天目十五
  - 巴达维
  - 舍利夫
  - 拉齐
  - 吴船长
  - 艾伯特
  - 埃泽
  - 松浦
  - 阿拉夫
  - 莫塞伊思
  - 阿圆
  - 石头
  - 百闻
  - 迈蒙
  - 掇星攫辰天君
  - 博易
  - 斯坦利
  - 毗伽尔
  - 诗筠
  - 慧心
  - 恶龙
  - 小仓澪
  - 知易
  - 恕筠
  - 克列门特
  - 大慈树王
  - 维多利亚
  - 黑田
  - 宁禄
  - 马姆杜
  - 西拉杰
  - 上杉
  - 阿尔卡米
  - 常九爷
  - 纯水精灵
  - 田铁嘴
  - 沙扎曼
  - 加萨尼
  - 克罗索
  - 莱斯格
  - 星稀
  - 阿巴图伊
  - 悦
  - 德田
  - 阿佩普
  - 埃尔欣根
  - 萨赫哈蒂
  - 洛伦佐
  - 深渊使徒
  - 塔杰·拉德卡尼
  - 泽田
  - 安西
  - 理水叠山真君
  - 萨齐因
  - 古田

api2model:
  - 空
  - 荧
  - 派蒙
  - 纳西妲
  - 阿贝多
  - 温迪
  - 枫原万叶
  - 钟离
  - 荒泷一斗
  - 八重神子
  - 艾尔海森
  - 提纳里
  - 迪希雅
  - 卡维
  - 宵宫
  - 莱依拉
  - 赛诺
  - 诺艾尔
  - 托马
  - 凝光
  - 莫娜
  - 北斗
  - 神里绫华
  - 雷电将军
  - 芭芭拉
  - 鹿野院平藏
  - 五郎
  - 迪奥娜
  - 凯亚
  - 安柏
  - 班尼特
  - 琴
  - 柯莱
  - 夜兰
  - 妮露
  - 辛焱
  - 珐露珊
  - 魈
  - 香菱
  - 达达利亚
  - 砂糖
  - 早柚
  - 云堇
  - 刻晴
  - 丽莎
  - 迪卢克
  - 烟绯
  - 重云
  - 珊瑚宫心海
  - 胡桃
  - 可莉
  - 流浪者
  - 久岐忍
  - 神里绫人
  - 甘雨
  - 戴因斯雷布
  - 优菈
  - 菲谢尔
  - 行秋
  - 白术
  - 九条裟罗
  - 雷泽
  - 申鹤
  - 迪娜泽黛
  - 凯瑟琳
  - 多莉
  - 坎蒂丝
  - 萍姥姥
  - 罗莎莉亚
  - 留云借风真君
  - 绮良良
  - 瑶瑶
  - 七七
  - 奥兹
  - 米卡
  - 夏洛蒂
  - 埃洛伊
  - 博士
  - 女士
  - 大慈树王
  - 三月七
  - 娜塔莎
  - 希露瓦
  - 虎克
  - 克拉拉
  - 丹恒
  - 希儿
  - 布洛妮娅
  - 瓦尔特
  - 杰帕德
  - 佩拉
  - 姬子
  - 艾丝妲
  - 白露
  - 星
  - 穹
  - 桑博
  - 伦纳德
  - 停云
  - 罗刹
  - 卡芙卡
  - 彦卿
  - 史瓦罗
  - 螺丝咕姆
  - 阿兰
  - 银狼
  - 素裳
  - 丹枢
  - 黑塔
  - 景元
  - 帕姆
  - 可可利亚
  - 半夏
  - 符玄
  - 公输师傅
  - 奥列格
  - 青雀
  - 大毫
  - 青镞
  - 费斯曼
  - 绿芙蓉
  - 镜流
  - 信使
  - 丽塔
  - 失落迷迭
  - 缭乱星棘
  - 伊甸
  - 伏特加女孩
  - 狂热蓝调
  - 莉莉娅
  - 萝莎莉娅
  - 八重樱
  - 八重霞
  - 卡莲
  - 第六夜想曲
  - 卡萝尔
  - 姬子
  - 极地战刃
  - 布洛妮娅
  - 次生银翼
  - 理之律者
  - 真理之律者
  - 迷城骇兔
  - 希儿
  - 魇夜星渊
  - 黑希儿
  - 帕朵菲莉丝
  - 天元骑英
  - 幽兰黛尔
  - 德丽莎
  - 月下初拥
  - 朔夜观星
  - 暮光骑士
  - 明日香
  - 李素裳
  - 格蕾修
  - 梅比乌斯
  - 渡鸦
  - 人之律者
  - 爱莉希雅
  - 爱衣
  - 天穹游侠
  - 琪亚娜
  - 空之律者
  - 终焉之律者
  - 薪炎之律者
  - 云墨丹心
  - 符华
  - 识之律者
  - 维尔薇
  - 始源之律者
  - 芽衣
  - 雷之律者
  - 苏莎娜
  - 阿波尼亚
  - 陆景和
  - 莫弈
  - 夏彦
  - 左然
