cnmodel:
- 派蒙
- 纳西妲
- 凯亚
- 温迪
- 荒泷一斗
- 娜维娅
- 阿贝多
- 钟离
- 枫原万叶
- 那维莱特
- 艾尔海森
- 八重神子
- 宵宫
- 芙宁娜
- 迪希雅
- 提纳里
- 莱依拉
- 卡维
- 诺艾尔
- 赛诺
- 林尼
- 莫娜
- 托马
- 神里绫华
- 凝光
- 北斗
- 可莉
- 柯莱
- 迪奥娜
- 莱欧斯利
- 芭芭拉
- 雷电将军
- 珊瑚宫心海
- 魈
- 五郎
- 胡桃
- 鹿野院平藏
- 安柏
- 琴
- 重云
- 达达利亚
- 班尼特
- 夜兰
- 丽莎
- 香菱
- 妮露
- 刻晴
- 珐露珊
- 烟绯
- 辛焱
- 早柚
- 迪卢克
- 砂糖
- 云堇
- 久岐忍
- 优菈
- 甘雨
- 夏洛蒂
- 流浪者
- 行秋
- 夏沃蕾
- 戴因斯雷布
- 闲云
- 白术
- 菲谢尔
- 申鹤
- 九条裟罗
- 雷泽
- 荧
- 空
- 嘉明
- 菲米尼
- 多莉
- 迪娜泽黛
- 琳妮特
- 凯瑟琳
- 米卡
- 坎蒂丝
- 萍姥姥
- 罗莎莉亚
- 埃德
- 爱贝尔
- 伊迪娅
- 留云借风真君
- 瑶瑶
- 绮良良
- 七七
- 式大将
- 奥兹
- 泽维尔
- 哲平
- 大肉丸
- 托克
- 蒂玛乌斯
- 昆钧
- 欧菲妮
- 仆人
- 塞琉斯
- 言笑
- 迈勒斯
- 希格雯
- 拉赫曼
- 阿守
- 杜拉夫
- 阿晃
- 旁白
- 克洛琳德
- 伊利亚斯
- 爱德琳
- 埃洛伊
- 远黛
- 德沃沙克
- 玛乔丽
- 劳维克
- 塞塔蕾
- 海芭夏
- 九条镰治
- 柊千里
- 阿娜耶
- 千织
- 笼钓瓶一心
- 回声海螺
- 叶德
- 卡莉露
- 元太
- 漱玉
- 阿扎尔
- 查尔斯
- 阿洛瓦
- 纳比尔
- 莎拉
- 迪尔菲
- 康纳
- 博来
- 博士
- 玛塞勒
- 阿祇
- 玛格丽特
- 埃勒曼
- 羽生田千鹤
- 宛烟
- 海妮耶
- 科尔特
- 霍夫曼
- 一心传名刀
- 弗洛朗
- 佐西摩斯
- 鹿野奈奈
- 舒伯特
- 天叔
- 艾莉丝
- 龙二
- 芙卡洛斯
- 莺儿
- 嘉良
- 珊瑚
- 费迪南德
- 祖莉亚·德斯特雷
- 久利须
- 嘉玛
- 艾文
- 女士
- 丹吉尔
- 天目十五
- 白老先生
- 老孟
- 巴达维
- 长生
- 拉齐
- 吴船长
- 波洛
- 艾伯特
- 松浦
- 乐平波琳
- 埃泽
- 阿圆
- 莫塞伊思
- 杜吉耶
- 百闻
- 石头
- 阿拉夫
- 博易
- 斯坦利
- 迈蒙
- 掇星攫辰天君
- 毗伽尔
- 花角玉将
- 恶龙
- 知易
- 恕筠
- 克列门特
- 西拉杰
- 上杉
- 大慈树王
- 常九爷
- 阿尔卡米
- 沙扎曼
- 田铁嘴
- 克罗索
- 悦
- 阿巴图伊
- 阿佩普
- 埃尔欣根
- 萨赫哈蒂
- 塔杰·拉德卡尼
- 安西
- 埃舍尔
- 萨齐因
- 三月七
- 陌生人
- 丹恒
- 希儿
- 瓦尔特
- 希露瓦
- 佩拉
- 娜塔莎
- 布洛妮娅
- 穹
- 星
- 虎克
- 素裳
- 克拉拉
- 符玄
- 白露
- 杰帕德
- 景元
- 姬子
- 藿藿
- 桑博
- 流萤
- 艾丝妲
- 卡芙卡
- 黑天鹅
- 桂乃芬
- 玲可
- 托帕
- 彦卿
- 浮烟
- 黑塔
- 驭空
- 螺丝咕姆
- 停云
- 镜流
- 帕姆
- 卢卡
- 史瓦罗
- 罗刹
- 真理医生
- 阿兰
- 阮•梅
- 明曦
- 银狼
- 青雀
- 乔瓦尼
- 伦纳德
- 公输师傅
- 黄泉
- 晴霓
- 奥列格
- 丹枢
- 砂金
- 尾巴
- 寒鸦
- 雪衣
- 可可利亚
- 青镞
- 半夏
- 银枝
- 米沙
- 大毫
- 霄翰
- 信使
- 费斯曼
- 爱德华医生
- 警长
- 猎犬家系成员
- 绿芙蓉
- 金人会长
- 维利特
- 维尔德
- 斯科特
- 卡波特
- 刃
- 岩明
- 浣溪
- 女声
- 男声
- 陆景和
- 莫弈
- 左然
- 夏彦


jpmodel:


enmodel:


api2model:
  - 空
  - 荧
  - 派蒙
  - 纳西妲
  - 阿贝多
  - 温迪
  - 枫原万叶
  - 钟离
  - 荒泷一斗
  - 八重神子
  - 艾尔海森
  - 提纳里
  - 迪希雅
  - 卡维
  - 宵宫
  - 莱依拉
  - 赛诺
  - 诺艾尔
  - 托马
  - 凝光
  - 莫娜
  - 北斗
  - 神里绫华
  - 雷电将军
  - 芭芭拉
  - 鹿野院平藏
  - 五郎
  - 迪奥娜
  - 凯亚
  - 安柏
  - 班尼特
  - 琴
  - 柯莱
  - 夜兰
  - 妮露
  - 辛焱
  - 珐露珊
  - 魈
  - 香菱
  - 达达利亚
  - 砂糖
  - 早柚
  - 云堇
  - 刻晴
  - 丽莎
  - 迪卢克
  - 烟绯
  - 重云
  - 珊瑚宫心海
  - 胡桃
  - 可莉
  - 流浪者
  - 久岐忍
  - 神里绫人
  - 甘雨
  - 戴因斯雷布
  - 优菈
  - 菲谢尔
  - 行秋
  - 白术
  - 九条裟罗
  - 雷泽
  - 申鹤
  - 迪娜泽黛
  - 凯瑟琳
  - 多莉
  - 坎蒂丝
  - 萍姥姥
  - 罗莎莉亚
  - 留云借风真君
  - 绮良良
  - 瑶瑶
  - 七七
  - 奥兹
  - 米卡
  - 夏洛蒂
  - 埃洛伊
  - 博士
  - 女士
  - 大慈树王
  - 三月七
  - 娜塔莎
  - 希露瓦
  - 虎克
  - 克拉拉
  - 丹恒
  - 希儿
  - 布洛妮娅
  - 瓦尔特
  - 杰帕德
  - 佩拉
  - 姬子
  - 艾丝妲
  - 白露
  - 星
  - 穹
  - 桑博
  - 伦纳德
  - 停云
  - 罗刹
  - 卡芙卡
  - 彦卿
  - 史瓦罗
  - 螺丝咕姆
  - 阿兰
  - 银狼
  - 素裳
  - 丹枢
  - 黑塔
  - 景元
  - 帕姆
  - 可可利亚
  - 半夏
  - 符玄
  - 公输师傅
  - 奥列格
  - 青雀
  - 大毫
  - 青镞
  - 费斯曼
  - 绿芙蓉
  - 镜流
  - 信使
  - 丽塔
  - 失落迷迭
  - 缭乱星棘
  - 伊甸
  - 伏特加女孩
  - 狂热蓝调
  - 莉莉娅
  - 萝莎莉娅
  - 八重樱
  - 八重霞
  - 卡莲
  - 第六夜想曲
  - 卡萝尔
  - 姬子
  - 极地战刃
  - 布洛妮娅
  - 次生银翼
  - 理之律者
  - 真理之律者
  - 迷城骇兔
  - 希儿
  - 魇夜星渊
  - 黑希儿
  - 帕朵菲莉丝
  - 天元骑英
  - 幽兰黛尔
  - 德丽莎
  - 月下初拥
  - 朔夜观星
  - 暮光骑士
  - 明日香
  - 李素裳
  - 格蕾修
  - 梅比乌斯
  - 渡鸦
  - 人之律者
  - 爱莉希雅
  - 爱衣
  - 天穹游侠
  - 琪亚娜
  - 空之律者
  - 终焉之律者
  - 薪炎之律者
  - 云墨丹心
  - 符华
  - 识之律者
  - 维尔薇
  - 始源之律者
  - 芽衣
  - 雷之律者
  - 苏莎娜
  - 阿波尼亚
  - 陆景和
  - 莫弈
  - 夏彦
  - 左然
